name: S3 Upload

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CFM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CFM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 # replace this with your aws-region

    - name: List
      run: |
        ls
    - name: AWS List
      run: |
       aws s3 ls
    - name: Copy files
      run: |
        aws s3 cp udacity-tamplate.zip s3://s3-hawebapp-cris/
       



  
