name: S3 Upload

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  deploy:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@master
    - name: Upload file to bucket
      uses: koraykoska/s3-upload-github-action@master
      env:
        FILE: ./templates/
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_ACCESS_KEY_ID: ${{ secrets.CFM_AWS_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.CFM_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1



  
